# Generated by Django 5.1.6 on 2025-03-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerinfo',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='sellerinfo',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='phone_number',
        ),
    ]
