version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: artiv
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@123
    ports:
      - "5432:5432"
  
  web:
    image: artiv-docker:latest
    container_name: atul-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@123@db:5432/artiv
