# Generated by Django 5.1.6 on 2025-04-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
