# Generated by Django 5.1.6 on 2025-04-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_artwork_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
