# Generated by Django 5.1.6 on 2026-08-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_artwork_end_date_alter_bid_bid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='ending_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
